### ISSUE TITLE
[minqlx.queue.log_exception] ERROR

### ISSUE THREAD

**Issue by AsphyxEvents** [mattiZed/minqlx-plugins#2]
spammed my console : 

[minqlx.queue.log_exception] ERROR: Traceback (most recent call last):
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_events.py", line 79, in dispatch
[minqlx.queue.log_exception] ERROR:     res = handler(_self.args, *_self.kwargs)
[minqlx.queue.log_exception] ERROR:   File "./minqlx-plugins/queue.py", line 197, in handle_configstring
[minqlx.queue.log_exception] ERROR:     player = self.player(index - 529)
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_plugin.py", line 268, in player
[minqlx.queue.log_exception] ERROR:     return minqlx.Player(name)
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_player.py", line 56, in __init__
[minqlx.queue.log_exception] ERROR:     .format(client_id))
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_player.py", line 123, in _invalidate
[minqlx.queue.log_exception] ERROR:     raise NonexistentPlayerError(e)
[minqlx.queue.log_exception] ERROR: minqlx._player.NonexistentPlayerError: Tried to initialize a Player instance of nonexistant player 4.

*_part2: *_

[minqlx.queue.log_exception] ERROR: Traceback (most recent call last):
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_events.py", line 79, in dispatch
[minqlx.queue.log_exception] ERROR:     res = handler(_self.args, *_self.kwargs)
[minqlx.queue.log_exception] ERROR:   File "./minqlx-plugins/queue.py", line 197, in handle_configstring
[minqlx.queue.log_exception] ERROR:     player = self.player(index - 529)
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_plugin.py", line 268, in player
[minqlx.queue.log_exception] ERROR:     return minqlx.Player(name)
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_player.py", line 56, in __init__
[minqlx.queue.log_exception] ERROR:     .format(client_id))
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_player.py", line 123, in _invalidate
[minqlx.queue.log_exception] ERROR:     raise NonexistentPlayerError(e)
[minqlx.queue.log_exception] ERROR: minqlx._player.NonexistentPlayerError: Tried to initialize a Player instance of nonexistant player 5.
broadcast: print "HM1983^7 connected\n"
HM1983 connected with Steam ID 76561198034985680
broadcast: print "HM1983^7 disconnected\n"
Client 2 connecting with 50 challenge ping
[minqlx.queue.log_exception] ERROR: Traceback (most recent call last):
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_events.py", line 79, in dispatch
[minqlx.queue.log_exception] ERROR:     res = handler(_self.args, *_self.kwargs)
[minqlx.queue.log_exception] ERROR:   File "./minqlx-plugins/queue.py", line 197, in handle_configstring
[minqlx.queue.log_exception] ERROR:     player = self.player(index - 529)
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_plugin.py", line 268, in player
[minqlx.queue.log_exception] ERROR:     return minqlx.Player(name)
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_player.py", line 56, in __init__
[minqlx.queue.log_exception] ERROR:     .format(client_id))
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_player.py", line 123, in _invalidate
[minqlx.queue.log_exception] ERROR:     raise NonexistentPlayerError(e)
[minqlx.queue.log_exception] ERROR: minqlx._player.NonexistentPlayerError: Tried to initialize a Player instance of nonexistant player 5.
broadcast: print "lnfst^7 connected\n"
lnfst connected with Steam ID 76561198006274665
Client 3 connecting with 25 challenge ping
[minqlx.queue.log_exception] ERROR: Traceback (most recent call last):
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_events.py", line 79, in dispatch
[minqlx.queue.log_exception] ERROR:     res = handler(_self.args, *_self.kwargs)
[minqlx.queue.log_exception] ERROR:   File "./minqlx-plugins/queue.py", line 197, in handle_configstring
[minqlx.queue.log_exception] ERROR:     player = self.player(index - 529)
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_plugin.py", line 268, in player
[minqlx.queue.log_exception] ERROR:     return minqlx.Player(name)
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_player.py", line 56, in __init__
[minqlx.queue.log_exception] ERROR:     .format(client_id))
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_player.py", line 123, in _invalidate
[minqlx.queue.log_exception] ERROR:     raise NonexistentPlayerError(e)
[minqlx.queue.log_exception] ERROR: minqlx._player.NonexistentPlayerError: Tried to initialize a Player instance of nonexistant player 6.
broadcast: print "CHEERS_PAL^7 connected\n"
CHEERS_PAL connected with Steam ID 76561198236602132
Client 4 connecting with 50 challenge ping
[minqlx.queue.log_exception] ERROR: Traceback (most recent call last):
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_events.py", line 79, in dispatch
[minqlx.queue.log_exception] ERROR:     res = handler(_self.args, *_self.kwargs)
[minqlx.queue.log_exception] ERROR:   File "./minqlx-plugins/queue.py", line 197, in handle_configstring
[minqlx.queue.log_exception] ERROR:     player = self.player(index - 529)
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_plugin.py", line 268, in player
[minqlx.queue.log_exception] ERROR:     return minqlx.Player(name)
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_player.py", line 56, in __init__
[minqlx.queue.log_exception] ERROR:     .format(client_id))
[minqlx.queue.log_exception] ERROR:   File "minqlx.zip/minqlx/_player.py", line 123, in _invalidate
[minqlx.queue.log_exception] ERROR:     raise NonexistentPlayerError(e)
[minqlx.queue.log_exception] ERROR: minqlx._player.NonexistentPlayerError: Tried to initialize a Player instance of nonexistant player 7.

**Comment by mattiZed** [comment]
It seems like you are running an old version of the plugin: this bug has been adressed already. Please update.
