### ISSUE TITLE
Queue plugin renders team locking useless

### ISSUE THREAD

**Issue by dsverdlo** [mattiZed/minqlx-plugins#4]
Hi Mr mattiZed.

It has come to my attention that servers with your queue plugin cannot effectively lock their servers anymore since your plugin switches them anyways. Could you maybe add a check to see if a team is locked before throwing players in? :-)

Cheers
Iou

**Comment by dsverdlo** [comment]
@Melodeiro forgot you took this plugin over. Here's a tag :-D

**Comment by Melodeiro** [comment]
Fixed in last commit: https://github.com/Melodeiro/minqlx-plugins_mattiZed/commit/b46859c7eda09f54c03310344edd6663f3aa62de
I think, issue can be closed.
